name: "Development CI/CD"

on: pull_request

jobs:
  linters:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: 3.0.3
          bundler-cache: true

      # Add or replace any other lints here
      - name: Lint Ruby files
        run: bin/rubocop -c .rubocop.yml --parallel

  tests:
    runs-on: self-hosted
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: 3.0.3
          bundler-cache: true

      # Add or replace test runners here
      - name: Run tests
        run: bin/rspec -fp

      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
          retention-days: 30
