name: Development CI/CD

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.5'
          - '3.1.3'
          - '3.2.1'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    # Add or replace any other lints here
    - name: Lint Ruby files
      run: bundle exec rubocop -c .rubocop.yml --parallel

    - name: Run Rspec
      run: bundle exec rspec -fp

    - name: Archive coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage
        retention-days: 30
